name: CI Validation (Dev)

on:
  pull_request:
    [cite_start]branches: [ "dev" ] # Critère : On Merge Request to dev 

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linting
        [cite_start]run: npm run lint

      - name: Run npm audit
        [cite_start]run: npm audit 

      - name: Snyk Security Analysis
        [cite_start]uses: snyk/actions/node@master 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Execute all tests
        [cite_start]run: npm test 

      - name: Build Docker images
        [cite_start]run: docker-compose build 

